services:
  frontend:
    image: sandrok0/e-commerce:frontend-latest
    ports:
      - "3000:80"
    depends_on:
      - backend
  backend:
    image: sandrok0/e-commerce:backend-latest
    ports:
      - "8000:80"
    depends_on:
      - db
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: shopdb
      MYSQL_USER: shopuser
      MYSQL_PASSWORD: userpassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./shopdb.sql:/docker-entrypoint-initdb.d/shopdb.sql
volumes:
  db_data: