
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"   # Mapping 3000 (host) to 80 (container), Nginx serves on 80
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    ports:
      - "8000:80"   # Apache runs on port 80 inside the container
    depends_on:
      - db

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: shopdb
      MYSQL_USER: shopuser
      MYSQL_PASSWORD: userpassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./shopdb.sql:/docker-entrypoint-initdb.d/shopdb.sql  # Initialize DB with this file on first run

volumes:
  db_data:
